name: 'Bug Report'
description: If something isn't working
labels:
  - kind/bug
  - status/triage
body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: 'Describe the bug'
      description: 'A clear and concise description of what the bug is.'
      placeholder: 'It bugs out when ...'
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: 'Expected behavior'
      description: 'What did you think should happen?'
      placeholder: 'I expected it to...'
  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: 'Actual Behavior with Screenshots'
      description: 'What did actually happen? Add screenshots, if applicable.'
      placeholder: 'It actually ...'
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: '  What are the steps to reproduce this issue?'
      description: 'How do you trigger this bug? Please walk us through it step by step.'
      placeholder:
        "Provide a link to a live example, or an unambiguous set of steps to reproduce this bug.\n
        Include code or configuration to reproduce, if relevant.\n
        1. Go to '...'\n
        2. Click on '....'\n
        3. Scroll down to '....'"
  - type: textarea
    id: additional-info
    validations:
      required: false
    attributes:
      label: ' Additional information'
      description: 'Include as many relevant details about the environment you experienced the bug in.'
      placeholder: "- Which devices are affected? ie Desktop, Table, Phone \n
        - Which browsers are affected? ie Chrome, Firefox, Safari, Edge \n
        - Which version are you using?"
